### ISSUE TITLE
ppa + install from ppa takes two rounds to resolve

### ISSUE THREAD

**Issue by asottile** [asottile/personal-puppet#1]
Not sure what the _correct_ way to do this is.

Here's the relevant code: https://github.com/asottile/personal-puppet/blob/dd299b25ddb5e9dae72eded0108d4493d20c90af/modules/packages/manifests/python.pp#L4-L5

**Comment by chriskuehl** [comment]
I think this is a good use for stages. I like to have two stages: `first` and `main`. In `first`, I make sure the apt sources are set up and `apt-get update` has run. Then the `main` stage can just assume that sources are set up and `apt-get update` has run.

Here's an example (not using the `apt` module for simplicity, but should have the same idea):

```puppet
## define this in your site.pp manifest
# add a stage before first
# e.g. https://github.com/ocf/puppet/blob/79c363a27a2fa0984289eafa2a3a3140d72b806b/manifests/site.pp#L6-L7
stage { 'first': before => Stage['main'] }

# all your first stage things have to happen in a class; for some reason, you
# can only set classes at a stage, not individual resources
include test_setupapt
include test_installpackages

# ocf equivalent: https://github.com/ocf/puppet/blob/3b42a13a538cdf051112711b6bea15f892683333/modules/ocf/manifests/apt.pp
class test_setupapt($stage = 'first') {
  file { '/etc/apt/sources.list.d/test.list':
    content => "deb https://www.ocf.berkeley.edu/~ckuehl/pre-commit stretch main\n",
  }
  ~> exec { '/usr/bin/apt-get update': refreshonly => true }
  notify { 'in the first stage': }
}

class test_installpackages {
  notify { 'in the main stage': }
}
```

When I run puppet the first time, you can see that it adds the file and triggers `apt-get update`:
```bash
ckuehl@raziel:~$ sudo puppet apply test.pp                
Notice: Compiled catalog for raziel.ckuehl.me in environment production in 0.15 seconds
Notice: /Stage[first]/Test_setupapt/File[/etc/apt/sources.list.d/test.list]/ensure: defined content as '{md5}d6896f60ec4e093f776599f3de771311'
Notice: /Stage[first]/Test_setupapt/Exec[/usr/bin/apt-get update]: Triggered 'refresh' from 1 events
Notice: in the first stage
Notice: /Stage[first]/Test_setupapt/Notify[in the first stage]/message: defined 'message' as 'in the first stage'
Notice: in the main stage
Notice: /Stage[main]/Test_installpackages/Notify[in the main stage]/message: defined 'message' as 'in the main stage'
Notice: Applied catalog in 1.23 seconds
```

When I run it again, nothing happens except the `notify`s (no `apt-get update` either, which is imo important to save time):
```bash
$ sudo puppet apply test.pp                
Notice: Compiled catalog for raziel.ckuehl.me in environment production in 0.16 seconds
Notice: in the first stage
Notice: /Stage[first]/Test_setupapt/Notify[in the first stage]/message: defined 'message' as 'in the first stage'
Notice: in the main stage
Notice: /Stage[main]/Test_installpackages/Notify[in the main stage]/message: defined 'message' as 'in the main stage'
Notice: Applied catalog in 0.04 seconds
```

Stages do kinda suck though because it's hard to depend on things across stages, e.g. [the Puppet docs](https://puppet.com/docs/puppet/5.3/lang_run_stages.html) talk more about the limitations, and say in particular "Due to these limitations, stages should only be used with the simplest of classes, and only when absolutely necessary. Mass dependencies like package repositories are effectively the only valid use case."

You could probably also solve this without stages if you're willing to add an `apt-get update` exec in the middle of that dependency chain.

**Comment by asottile** [comment]
Ended up finding `Exec['apt_update']` which `apt::source` and `apt::ppa` were triggering a refresh of.  Seems to work as I'd want: https://github.com/asottile/personal-puppet/commit/bb0adb1e9194cf519f6170c3e900f98c3efb6b70
